### ISSUE TITLE
AC2889/10 stops sending updates

### ISSUE THREAD

**Issue by ablohm** [kongo09/philips-airpurifier-coap#39]
After updating from v0.10.1 to the latest v0.10.7 my AC2889/10 does not send any updates. I connects when HA restarts and reads the current values from the device. It can also be turned on and off but the current status is never updated in HA. So if I turn the device on the switch will be reset to off shortly after. Also values for PM25 and IAI will just be read once at startup and never update.

The log shows nothing unusual. I'm running core-2022.5.4 on Home Assistant OS 8.0.

v0.10.1 was running fine for me.

UPDATE: After trying to reinstall the integration I'm getting this error in the log:

`Error occurred loading configuration flow for integration philips_airpurifier_coap: cannot import name 'CoAPClient' from 'aioairctrl' (/usr/local/lib/python3.9/site-packages/aioairctrl/__init__.py)`

**Comment by KrizzeOne** [comment]
I can't really help you, but I'm struggling to connect my AC2889 to HA (see #34)
Can you tell me what you did in order to connect it successfully with 0.10.1?

**Comment by kongo09** [comment]
The biggest difference from 0.10.1 to 0.10.7 is that `aioairctrl` is now loaded as a library from pypi. Maybe this installation didn't work properly for @ablohm . Did you maybe manually install `aioairctrl` on your machine? If so, where from and in what version?

**Comment by ablohm** [comment]
After updating to the latest core-2022.5.5 and Home Assistant OS 8.1 I could reinstall the latest version of the integration successfully and the data started updating. Sadly the updates stopped after a few hours and have not worked since. I restarted HA and the air purifier to no avail. The data seems to be read only once after the restart of HA.

**Comment by ablohm** [comment]
Tonight the purifier started sending updates, but again stopped after a few hours. In the log I see this message:
`Timeout, host 192.168.1.100 looks like a Philips AirPurifier but doesn't answer, aborting`

**Comment by kongo09** [comment]
@ablohm The timeout message you observe has nothing to do with your device failing to update. This is the timeout message that happens when HomeAssistant discovers something on the network that looks like a Philips AirPurifier (based on DHCP) and then the integration tries to talk to it to find out if it can auto-configure it. If the device doesn't answer (because it is not an AirPurifier or it is one with a connectivity problem), then the message above is written to the log.

As you have a configured device already, you can safely ignore this. If HA would have managed to talk to the device, it would have checked if it knows it already and then - in your case - aborted anyhow.

**Comment by kongo09** [comment]
Concerning your other observations, this looks very much like the connectivity problem that bugs us all. It's beyond me to fix this, so I'll close this issue.

**Comment by ablohm** [comment]
The IP address from the timeout message is the correct address of the purifier. The integration was configured with this addess, it is not a new device that was discovered by HA.

**Comment by kongo09** [comment]
Yes, that's what I tried to say. It discovers your existing device.
